CuaHangThucPham/Controllers/QuanLyLoaiThanhVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuaHangThucPham.Models;


namespace CuaHangThucPham.Controllers
{
    public class QuanLyLoaiThanhVienController : Controller
    {
        QuanLyEntities db = new QuanLyEntities();
        // GET: QuanLyLoaiThanhVien
        public ActionResult Index()
        {
            var lstLTV = db.LoaiThanhViens;
            return View(lstLTV);
        }
        [HttpGet]
        public ActionResult TaoMoi()
        {
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(LoaiThanhVien ltv)
        {
            db.LoaiThanhViens.Add(ltv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //lay ncc can chinh sua
            if (id == null) {
                Response.StatusCode = 404;
                return null;
            }
            LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (ltv == null) {
                return HttpNotFound();
            }
            return View(ltv);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(LoaiThanhVien ltv)
        {
            db.Entry(ltv).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Xoa(int? id)
        {
            //lay ncc can chinh sua
            if (id == null) {
                Response.StatusCode = 404;
                return null;
            }
            LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (ltv == null) {
                return HttpNotFound();
            }
            return View(ltv);
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            LoaiThanhVien ltv = db.LoaiThanhViens.SingleOrDefault(n => n.MaLoaiTV == id);
            if (ltv == null) {
                return HttpNotFound();
            }
            db.LoaiThanhViens.Remove(ltv);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CuaHangThucPham/Views/QuanLyLoaiThanhVien/ChinhSua.cshtml
@model CuaHangThucPham.Models.LoaiThanhVien

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Chỉnh sửa </h2>

@using (Html.BeginForm("ChinhSua", "QuanLyLoaiThanhVien")) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Loại thành viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("MaLoaiTV", Model.MaLoaiTV)

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UuDai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UuDai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UuDai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

CuaHangThucPham/Views/QuanLyLoaiThanhVien/Index.cshtml
@using CuaHangThucPham.Models
@model IEnumerable<LoaiThanhVien>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //khoi tao control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 20);
}

<h2>Loại thành viên</h2>

@grid.GetHtml(
    tableStyle: "gridTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "girdAltRow",
    columns: grid.Columns(
        grid.Column("MaLoaiTV", "Mã loại thành viên"),
        grid.Column("TenLoai", "Tên loại thành viên"),
        grid.Column("UuDai", "Ưu đãi"),
        grid.Column(format: p => @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { id = p.MaLoaiTV })),
        grid.Column(format: p => Html.ActionLink("Xoá", "Xoa", new { id = p.MaLoaiTV }))

        )

    )
<a href="@Url.Action("TaoMoi","QuanLyLoaiThanhVien")" class="TaoMoi">Thêm mới</a>
@*css cho tung style cua table*@
<style>
    .gridTable {
        width:100%;
        border: 1px solid #808080;

    }
    .gridTable td {
        border:1px solid #999999;
    }
    .gridHead {
        background-color:green;
    }
    .gridHead>th>a {

        color:white;

    }
    .gridFooter {
        font-weight:bold;
    }
    .TaoMoi {
        background: #333;
        padding: 10px 1.5em;
        border-radius: 7px;
        -moz-border-radius: 7px;
        -webkit-border-radius: 7px;
        -o-border-radius: 7px;
        font-size: 1em;
        color: #fff;
        text-decoration: none;
        display: block;
        font-weight:600;
        text-align: center;
        width: 12%;
        margin: 3em 3em 0 auto;

    }
    @*.gridRow {
        color:white;
        background-color:blueviolet;
    }
    .girdAltRow{
        color:white;
        background-color:orange;
    }*@
</style>
<style>
    .FooterAdmin {
        display: none;
    }
</style>

CuaHangThucPham/Views/QuanLyLoaiThanhVien/TaoMoi.cshtml
@model CuaHangThucPham.Models.LoaiThanhVien


@{
    ViewBag.Title = "TaoMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Thêm </h2>

@using (Html.BeginForm("TaoMoi", "QuanLyLoaiThanhVien")) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Loại thành viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UuDai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UuDai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UuDai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

CuaHangThucPham/Views/QuanLyLoaiThanhVien/Xoa.cshtml
@model CuaHangThucPham.Models.LoaiThanhVien


@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Xoá </h2>

@using (Html.BeginForm("Xoa", "QuanLyLoaiThanhVien")) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Loại thành viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("MaLoaiTV", Model.MaLoaiTV)

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UuDai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UuDai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UuDai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Xoá" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>