CuaHangThucPham/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuaHangThucPham.Models;

namespace CuaHangThucPham.Controllers
{
    public class AdminController : Controller
    {
        QuanLyEntities db = new QuanLyEntities();

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();// lấy số người truy cập từ application
            ViewBag.SoNguoiOnline = HttpContext.Application["SoNguoiOnline"].ToString();
            ViewBag.TongThanhVien = TongThanhVien();
            ViewBag.ThongKeDoanhThu = ThongKeDoanhThu();// thống kê doanh thu
            ViewBag.ThongKeDonHang = ThongKeDonHang(); // thống kê đơn hàng
            ViewBag.ThongKeSanPham = ThongKeSanPham(); // thống kê số lượng sản phẩm t
            ViewBag.ThongKeLoaiSanPham = ThongKeLoaiSanPham();
            return View();
        }
        public decimal? ThongKeDoanhThu()
        {
            decimal? TongDoanhThu = db.ChiTietDonDatHangs.Sum(n => n.DonGia * n.SoLuong);
            return TongDoanhThu;
        }

        public double ThongKeDonHang()
        {
            //Đếm đơn đặt hàng
            double sl = db.DonDatHangs.Count();
            return sl;
        }

        public double TongThanhVien()
        {
            double slTV = db.ThanhViens.Count();
            return slTV;
        }
        public int ThongKeSanPham()
        {
            // đếm số lượng sản phẩm
            int sanpham = db.SanPhams.Sum(n => n.SoLuongTon).Value;
            return sanpham;
        }
        public double ThongKeLoaiSanPham()
        {
            // đếm đơn đặt hàng
            double slncc = db.LoaiSanPhams.Count();
            return slncc;
        }


        public decimal? ThongKeDoanhThuTheoThang(int Thang, int Nam)
        {
            var lstDDH = db.DonDatHangs.Where(n => n.NgayDat.Value.Month == Thang && n.NgayDat.Value.Year == Nam);
            decimal? TongTien = 0;
            //Duyệt chi tiết đơn hàng theo điều kiện
            foreach (var item in lstDDH) {
                TongTien += item.ChiTietDonDatHangs.Sum(n => n.DonGia * n.SoLuong);
            }
            return TongTien;
        }
        [HttpPost]
        public ActionResult Index(FormCollection f)
        {
            int Thang = Convert.ToInt32(f["txtThang"].ToString());
            int Nam = Convert.ToInt32(f["txtNam"].ToString());
            decimal? tongtien = ThongKeDoanhThuTheoThang(Thang, Nam);
            return Content(tongtien.ToString());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CuaHangThucPham/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuaHangThucPham.Models;
using PagedList;

namespace CuaHangThucPham.Controllers
{
    public class TimKiemController : Controller
    {
        QuanLyEntities db = new QuanLyEntities();
        // GET: TimKiem
        [HttpGet]
        public ActionResult KQTimKiem(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET") {
                page = 1;
            }
            //thuc hien chuc nang phan trang
            //tao bien so san pham tren trang
            int PageSize = 6;
            //so trang hien tai
            int PageNumber = (page ?? 1);
            //tim kiem theo ten san pham
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(lstSP.OrderBy(n => n.TenSP).ToPagedList(PageNumber, PageSize));
        }
        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
            //goi ve ham get tim kiem
            return RedirectToAction("KQTimKiem", new { @sTuKhoa = sTuKhoa });
        }
    }
}

CuaHangThucPham/Views/Layout/AdminLayout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Trang quản lý</title>
    <title>Trang quản lý</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/CssAdmin/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom CSS -->
    <link href="~/Content/CssAdmin/css/style.css" rel='stylesheet' type='text/css' />
    <!-- Graph CSS -->
    <link href="~/Content/CssAdmin/css/font-awesome.css" rel="stylesheet">
    <!-- jQuery -->
    <!-- lined-icons -->
    <link rel="stylesheet" href="~/Content/CssAdmin/css/icon-font.min.css" type='text/css' />
    <!-- //lined-icons -->
    <!-- chart -->
    <script src="~/Content/CssAdmin/js/Chart.js"></script>
    <link href="~/Content/jquery.bxslider.css" rel="stylesheet" />
    <!-- //chart -->
    <!--animate-->
    <link href="~/Content/CssAdmin/css/animate.css" rel="stylesheet" type="text/css" media="all">
    <script src="~/Content/CssAdmin/js/wow.min.js"></script>
    <link href="~/Content/AdminLayout/css/bootstrap.css" rel="stylesheet" type='text/css' />
    <!-- Custom Theme files -->
    <link href="~/Content/AdminLayout/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/Content/AdminLayout/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/Content/AdminLayout/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <script>
        $(document).ready(function (c) {
            $('.alert-close').on('click', function (c) {
                $('.calender-left').fadeOut('slow', function (c) {
                    $('.calender-left').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close1').on('click', function (c) {
                $('.calender-right').fadeOut('slow', function (c) {
                    $('.calender-right').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close2').on('click', function (c) {
                $('.graph').fadeOut('slow', function (c) {
                    $('.graph').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close3').on('click', function (c) {
                $('.site-report').fadeOut('slow', function (c) {
                    $('.site-report').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close4').on('click', function (c) {
                $('.total-sale').fadeOut('slow', function (c) {
                    $('.total-sale').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close5').on('click', function (c) {
                $('.to-do').fadeOut('slow', function (c) {
                    $('.to-do').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close7').on('click', function (c) {
                $('.user-trends').fadeOut('slow', function (c) {
                    $('.user-trends').remove();
                });
            });
        });
    </script>
    <script>
        $(document).ready(function (c) {
            $('.alert-close6').on('click', function (c) {
                $('.world-map').fadeOut('slow', function (c) {
                    $('.world-map').remove();
                });
            });
        });
    </script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-48014931-1', 'codyhouse.co');
        ga('send', 'pageview');

        jQuery(document).ready(function ($) {
            $('.close-carbon-adv').on('click', function () {
                $('#carbonads-container').hide();
            });
        });
    </script>
    <script src="~/Content/AdminLayout/js/zingchart.min.js"></script>
    <script src="~/Content/AdminLayout/js/zingchart.jquery.js"></script>
    <script src="~/Content/AdminLayout/js/jquery.easydropdown.js"></script>
    <script src="~/Content/AdminLayout/js/jquery.nicescroll.js"></script>

    <link href="~/Content/AdminLayout/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/AdminLayout/js/jquery.vmap.js" type="text/javascript"></script>
    <script src="~/Content/AdminLayout/js/jquery.vmap.world.js" type="text/javascript"></script>
    <script src="~/Content/AdminLayout/js/jquery.vmap.sampledata.js" type="text/javascript"></script>
    @*chen font icon vao layout*@
    <link href="~/Content/CssFont/css/font-awesome.min.css" rel="stylesheet" />
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#vmap').vectorMap({
                map: 'world_en',
                backgroundColor: '#333333',
                color: '#ffffff',
                hoverOpacity: 0.7,
                selectedColor: '#666666',
                enableZoom: true,
                showTooltip: true,
                values: sample_data,
                scaleColors: ['#C8EEFF', '#006491'],
                normalizeFunction: 'polynomial'
            });
        });
    </script>
    <!----Calender -------->
    <link rel="stylesheet" href="~/Content/AdminLayout/css/clndr.css" type="text/css" />
    <script src="~/Content/AdminLayout/js/underscore-min.js"></script>
    <script src="~/Content/AdminLayout/js/moment-2.2.1.js"></script>
    <script src="~/Content/AdminLayout/js/clndr.js"></script>
    <script src="~/Content/AdminLayout/js/site.js"></script>
    <!----End Calender -------->
    <script src="~/Content/AdminLayout/js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#horizontalTab,#horizontalTab1,#horizontalTab2').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true   // 100% fit in a container
            });
        });
    </script>
    <style>
        .html {
            background-image: linear-gradient(45deg, rgb(116, 122, 138, 0.5), rgb(107, 135, 227, 0.5)), url(https://lh3.googleusercontent.com/proxy/GBvkzUkR7pP8DR6DcpfQSushcOlGczG2gPw8kI2OJ-3bzfbIOCL-jiOyRqr7_gF9qNN7tn739NQFdd6gOV5MnJ-fRwAuR1UopkEJxSlWq6mB6O0dm5_92HlsMunOTjaitro);
        }
    </style>
    <link href="~/Content/AdminLayout/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/Content/AdminLayout/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/Content/AdminLayout/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="col-md-3 side-bar">
            <div class="logo text-center">
                <a href="@Url.Action("Index","Admin")"><img src="~/hinhanh/cholon.png" alt="" /></a>
            </div>
            <div class="navigation">
                <h3>Danh mục</h3>
                <ul>
                    <li><a href="@Url.Action("Index","QuanLySanPham")">Quản lý sản phẩm</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("NhapHang","PhieuNhap")">Nhập hàng</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("DSSPHetHang","PhieuNhap")">Sản phẩm sắp hết hàng</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("ChuaGiao","DonDatHang")">Đơn đặt hàng</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("Index","NhaCungCap")">Nhà cung cấp</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("Index","QuanLyLoaiSanPham")">Loại sản phẩm</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("Index","QuanLyLoaiThanhVien")">Loại thành viên</a></li>
                </ul>
                <ul>
                    <li><a href="@Url.Action("Index","QuanLyTaiKhoan")">Thành viên</a></li>
                </ul>

            </div>
           
        </div>
        <div class="col-md-9 content">

            
            <div class="clearfix"></div>

            @RenderBody()
           

        </div>
        <div class="clearfix"></div>
    </div>
    <div class="footer">
        <div class="copyright text-center">
            <p>Copyright © 2021 Vương Store All rights reserved</p>
        </div>
    </div>
</body>
</html>

CuaHangThucPham/Views/Layout/HeaderTopPartial.cshtml
@using CuaHangThucPham.Models

<div class="agileits_header">
    <div class="container">
        <div class="agile-login">
            <ul>
                @if (Session["TaiKhoan"] != null && Session["TaiKhoan"].ToString() != "") {
                    ThanhVien tv = (ThanhVien)Session["TaiKhoan"];
                    <li style="margin-bottom:10px; color:white">Chào @tv.HoTen</li>
                    <li>@Html.ActionLink("Đăng Xuất", "DangXuat", "Home")</li>
                }
                else {
                    <li><a href="@Url.Action("DangNhap", "Home")">Đăng nhập</a></li>
                    <li><a href="@Url.Action("DangKy", "Home")">Đăng ký</a></li>

                }

            </ul>
        </div>
        @*chen partial view gio hang vao layout (tach gio hang sang 1 partial view moi)*@
        @Html.Action("GioHangPartial", "GioHang")
        <div class="clearfix"> </div>
    </div>
</div>

CuaHangThucPham/Views/Layout/HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Chào mừng bạn đến với chợ lớn abc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Super Market Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet">
    <script src="~/Content/js/jquery-1.11.1.min.js"></script>
    <link href='//fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="~/Content/js/move-top.js"></script>
    <script type="text/javascript" src="~/Content/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
</head>

<body>
    <!-- header -->

    @Html.Partial("~/Views/Layout/HeaderTopPartial.cshtml")
   

    <div class="logo_products">
        <div class="container">
            <div class="w3ls_logo_products_left1">
                <ul class="phone_email">
                    <li><i class="fa fa-phone" aria-hidden="true"></i>Hỗ trợ khách hàng: (+084)123 456</li>

                </ul>
            </div>
            <div class="w3ls_logo_products_left">
                <h1><a href="@Url.Action("Index","Home")">Chợ lớn abc</a></h1>
            </div>
            <div class="w3l_search">
                @using (Html.BeginForm("LayTuKhoaTimKiem", "TimKiem")) {
                    <input type="search" name="sTuKhoa" placeholder="Nhập sản phẩm bạn cần tìm ... " required="">
                    <button type="submit" class="btn btn-default search" aria-label="Left Align">
                        <i class="fa fa-search" aria-hidden="true"> </i>
                    </button>
                    <div class="clearfix"></div>
                }
            </div>

            <div class="clearfix"> </div>
        </div>
    </div>

    @Html.Action("MenuPartial", "Home")
    <div class="skdslider">
        <ul id="demo1">
            <li>
                <img src="~/hinhanh/sieuthi2.jpg" alt="" />
                <!--Slider Description example-->
                <div class="slide-desc">
                    <h3>Các sản phẩm được cam kết tiêu chuẩn quốc gia</h3>
                </div>
            </li>
        </ul><ul class="slide-navs" style="margin-left: -24px;"><li class="slide-nav-0"><a></a></li><li class="slide-nav-1"><a></a></li><li class="slide-nav-2 current-slide"><a></a></li></ul><a class="prev"></a><a class="next"></a><a class="play-control pause" style="display: none;"></a>
    </div>
   
    @RenderBody()
   
    <!-- //footer -->
    <div class="footer">
        <div class="container">
            <div class="w3_footer_grids">
                <div class="col-md-3 w3_footer_grid">
                    <h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tiếp xúc</font></font></h3>

                    <ul class="address">
                        <li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">123 HHH </font></font><span><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thành phố Đà Nẵng</font></font></span></li>
                        <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:tnhuy1497@gmail.com"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">tnhuy1497@gmail.com</font></font></a></li>
                        <li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">(+084) 123 456</font></font></li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thông tin</font></font></h3>
                    <ul class="info">
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Về chúng tôi</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Liên hệ chúng tôi</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Câu hỏi thường gặp</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sản phẩm đặc biệt</font></font></a></li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Hồ sơ</font></font></h3>
                    <ul class="info">
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cửa hàng</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="@Url.Action("GioHangPartial", "GioHang")"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Giỏ hàng của tôi</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="@Url.Action("DangNhap", "Home")"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Đăng nhập</font></font></a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="@Url.Action("DangKy", "Home")"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tạo tài khoản</font></font></a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

        <div class="footer-copy">


        </div>

    </div>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/js/bootstrap.min.js"></script>

    <!-- top-header and slider -->
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
    <script src="~/Content/js/minicart.min.js"></script>
    <script>
        // Mini Cart
        paypal.minicart.render({
            action: '#'
        });

        if (~window.location.search.indexOf('reset=true')) {
            paypal.minicart.reset();
        }
    </script>
    <!-- main slider-banner -->
    <script src="~/Content/js/skdslider.min.js"></script>
    <link href="~/Content/css/skdslider.css" rel="stylesheet">
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#demo1').skdslider({ 'delay': 5000, 'animationSpeed': 2000, 'showNextPrev': true, 'showPlayButton': true, 'autoSlide': true, 'animationType': 'fading' });

            jQuery('#responsive').change(function () {
                $('#responsive_wrapper').width(jQuery(this).val());
            });

        });
    </script>
    <!-- //main slider-banner -->
</body>
</html>